version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./app:/app
    php:
        container_name: php
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./app:/app
    mysql:
        image: mariadb:latest
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=api
            - MYSQL_PASSWORD=secret
            - MYSQL_DATABASE=api
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - "3306:3306"
        restart: always

volumes:
  mysqldata: {}
